# Generated by Django 5.0.3 on 2024-03-09 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambrosia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(through='ambrosia.RecipeIngredient', to='ambrosia.ingredient'),
        ),
    ]
